apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: 
  labels:
    app: 
    tenant: team-a
spec:
  replicas: 4
  selector:
    matchLabels:
      app: 
      tenant: team-a
  template:
    metadata:
      labels:
        app: 
        tenant: team-a
    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort: 
              name: 
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace:
  labels:
    app:
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 
      targetPort: 
  type: ClusterIP

