apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu
  namespace: 
  labels:
    type: gpu
    tenant: team-x
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 3
  selector:
    matchLabels:
      type: gpu
      tenant: team-x
  template:
    metadata:
      labels:
        type: gpu
        tenant: team-x
    spec:
      containers:
        - name: gpu
          image:                 #YOUR_IMAGE
          ports:
            - containerPort: 80
              name: gpu
---
apiVersion: v1
kind: Service
metadata:
  name:    
  namespace: 
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: gpu
  type: ClusterIP

