apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace:
  labels:
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name:
          image:
          ports:
            - containerPort: 
              name: 
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace:
  labels:
    app: 
spec:
  selector:
    app:
  ports:
    - protocol: TCP
      port: 
      targetPort: 
  type: ClusterIP

