apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: database
  labels:
    app: mysql
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
  serviceName:      #YOUR_SERVICE_NAME
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.4.5
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name:       #CUSTOMIZE
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name:      #SECRET_NAME
              key: password
  volumeClaimTemplates:
      - metadata:
         name:  #VLOUMEMOUNTS_NAME
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage:      #CUSTOMIZE
          storageClassName:    #PV_NAME
---
apiVersion: v1
kind: Service
metadata:
  name:   #CUSTOMIZE
  namespace: database
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql
  type: ClusterIP

